//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_users
    {
        public int Admin_ID { get; set; }
        public string Admin_name { get; set; }
        public string Admin_pass { get; set; }
    }
}
