//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmacyEntities : DbContext
    {
        public PharmacyEntities()
            : base("name=PharmacyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_users> Admin_users { get; set; }
        public virtual DbSet<expens> expenses { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<sale> sales { get; set; }
    }
}
